### ISSUE TITLE
Also writing to a .scp file will be cool

### ISSUE THREAD

**Issue by FredWe** [vesis84/kaldi-io-for-python#11]
Hi @vesis84 ,
When writing a feature matrix to a .ark file, it might be helpful to generate the corresponding .scp file to indicate positions. 
Like (the guys do here)[http://kaldi-to-matlab.gforge.inria.fr/], that will complete this tool's functionality.
BTW, It's a great tool, thank you. Tests are also great.

**Comment by vesis84** [comment]
Hi, okay, I see the merits... 
Actually, when I needed to write as 'ark,scp', i was using 
the workaround by writing to a pipe-string like this: 
`"ark:| copy-feats ark:- ark,scp:<some_ark>,<some_scp>"`
(i.e. it can be done without an explicit implementation of 'scp' output)

**Comment by vesis84** [comment]
Other thing would be, having and 'ark' file, do be able to generate an 'scp' file ex-post... This might be useful... And there is no implementation for it yet... Is this what you would need is it the abovementioned?

**Comment by FredWe** [comment]
Yes, that's exactly what i need.
Thank you for your explanation.
