### ISSUE TITLE
Updated kaldi_io can not read from pipe (python3)

### ISSUE THREAD

**Issue by wsstriving** [vesis84/kaldi-io-for-python#12]
Hi Karel,
     It's nice to support python3, I tested the new kaldi_io script, however, though it works fine for directly reading  "feats.ark",  it will fail when reading from the stream "ark:apply-cmvn-sliding --center=true ark:feats.ark ark:- |",  line 49 will throw an error as

`fd = os.popen(file[:-1], 'rb')
  File "/cm/shared/apps/python/3.6/lib/python3.6/os.py", line 970, in popen
  raise ValueError("invalid mode %r" % mode)'

This may be caused by the difference of stdin/out between python2 and python3.

**Comment by vesis84** [comment]
Hi, thanks for letting me know... After looking closer into it, 
it seems that this will not be trivial to resolve...

In python3, the os.popen() supports only the transfers of utf-8 strings
(i.e. it does not accept the 'wb' mode of file opening only the 'r' mode,
which cannot be used to write the byte-strings b'...').

In python2, there was no such problem as the 'string' and 'byte-string' is the same type.
Do you know any clean solution? Or would it be fine to support pipe-ing just for python 2.x ?

**Comment by vesis84** [comment]
Hi, finally I found a way how to support pipes both for pyhon2 and python3. Let me know, if there are some more problems... K.

**Comment by wsstriving** [comment]
Great! Thanks~
