### ISSUE TITLE
UTF8 decoding problem and accent management

### ISSUE THREAD

**Issue by TParcollet** [vesis84/kaldi-io-for-python#14]
Hi !

First of all, thanks you for this great job ! However, I had to transform every decode() in kaldi-io.py in decode('latin-1') in order to deal with French accents. I also had to comment an assertion that was checking for only non accentuated characters. It would be cool if you could bring this accentuation management for foreigners !

**Comment by vesis84** [comment]
Hi, can you please provide an example demonstrating the issue? (and possibly a solution). I guess that that 'latin-1' charset would not be universal fix-up, we should better go for 'utf8' and make it work both for python2 and python3 somehow... If you convert your inputs to utf8, is the problem still there? Best! K.

**Comment by TParcollet** [comment]
Sure ! Sorry for the late reply ! I haven't tried a lot of workaround, and since I just wanted it to work my solution is as follows:
![capture d ecran 2018-06-06 a 11 33 33](https://user-images.githubusercontent.com/11910731/41029999-90ef55e0-697d-11e8-9a84-02a1966de9c3.png)

For the example what do you need ? I can just say for now that a key "archevêquedegitega-ester2" would not work.

Regards,
Titouan.

**Comment by vesis84** [comment]
Okay, finally, i found time to look into it... 

And, it is fixed in this commit: https://github.com/vesis84/kaldi-io-for-python/commit/8716d2bb3f30a29f684b9ac6d277dfcd5ce2094d

Thank you for reporting the problem.
All the best,
Karel

**Comment by vesis84** [comment]
Okay, good, I used your string for the debugging...
Thank you,
Karel

Dne 06-Jun-18 v 10:38 Parcollet Titouan napsal(a):

**Comment by TParcollet** [comment]
Great ! Thanks you

**Comment by qmeeus** [comment]
Is this issue solved. I got this:
```python
Exception in main training loop: 'utf-8' codec can't decode byte 0xa5 in position 1: invalid start byte
  File "~/bin/anaconda3/envs/espnet/lib/python3.6/site-packages/torchaudio/kaldi_io.py", line 41, in _convert_method_output_to_tensor
    for key, np_arr in fn(file_or_fd):
  File "~/repos/kaldi-io-for-python/kaldi_io/kaldi_io.py", line 363, in read_mat_ark
    mat = read_mat(fd)
  File "~/kaldi-io-for-python/kaldi_io/kaldi_io.py", line 413, in read_mat
    binary = fd.read(2).decode()
```
Then this, after adding `latin-1` encoding to the problematic line, I got:
```python3
AssertionError
  File "~/bin/anaconda3/envs/espnet/lib/python3.6/site-packages/torchaudio/kaldi_io.py", line 41, in _convert_method_output_to_tensor
    for key, np_arr in fn(file_or_fd):
  File "~/repos/kaldi-io-for-python/kaldi_io/kaldi_io.py", line 363, in read_mat_ark
    mat = read_mat(fd)
  File "~/repos/kaldi-io-for-python/kaldi_io/kaldi_io.py", line 417, in read_mat
    assert(binary == ' [') 
```
