### ISSUE TITLE
Paths as keys for Matrices

### ISSUE THREAD

**Issue by RicherMans** [vesis84/kaldi-io-for-python#15]
Hey Karel,
since the humble beginnings of this script, the `read_key` function only supported keys without a `/` symbol. I was just wondering, is there a reason why it is like that, since kaldi itself supports keys with `/` in them, e.g. `audio/file.wav`, but kaldi_io does not ?

Otherwise, I just propose to change line 115 to:

```python
assert(re.match('^[\/.a-zA-Z0-9_-]+$',key) != None) 
```

**Comment by vesis84** [comment]
Okay, yes, there is no particular reason for disallowing slashes in ark-keys. This issue is now resolved in e7c94bc
