### ISSUE TITLE
It cannot use for python3

### ISSUE THREAD

**Issue by YihengJiang** [vesis84/kaldi-io-for-python#17]
first ,thank you for your work.
I have saw that you make capability for python3,but in kaldi_io.py,it sames that you have not revise code. And as the matter of fact,I can not run kaldi_io.py in python3. If it really could run on python3,could you give me some advise for how to use it.Before now,I have try to modify code to fit for python3,but it does not work.
the primary problem is str and byte which are different from python2
thank you,hope the response!!

**Comment by vesis84** [comment]
Strange, for me it works (the unittests pass both for 'python2' and 'python3') ... Maybe you have done something wrong, or used an old version?
Best, K.

**Comment by YihengJiang** [comment]
thanks your help,author!
I  find that i use the old version, now I change it and it could work normally.

**Comment by wayne0908** [comment]
Can this be used in windows?

**Comment by vesis84** [comment]
probably yes, in CYGWIN? but compiling/using Kaldi in windows can be problematic...
