### ISSUE TITLE
read compressed features 'CM '

### ISSUE THREAD

**Issue by twistedmove** [vesis84/kaldi-io-for-python#18]
Hi, is there a way to read compressed feature matrix? thanks.

**Comment by vesis84** [comment]
Yes, it sholud work, you use normal matrix reading function. But there are 3 types of compressed matrices, and only one of them is currently supported... If this is your case, you can decompress them on-the-fly  by  opening the archive as 'copy-feats ark:comppressed.ark ark:- |'... 
Does it solve your problem?
K.

**Comment by vesis84** [comment]
Loading of Compressed matrices is already supported...
