### ISSUE TITLE
Compressed matrices leads to `sample_size` not defined

### ISSUE THREAD

**Issue by jfainberg** [vesis84/kaldi-io-for-python#2]
If the matrix type is CM, then the `sample_size` assertions will fail because we never set `sample_size`.

Not sure what the `sample_size` is for CM, or whether it should simply complain?

Either way I'm happy to make a pull request.

**Comment by hajix** [comment]
Hi

accepting RichMans pull request solved the issue.

thanks

**Comment by RicherMans** [comment]
@hajix can you give me a hint which kaldi class it is? In the copy-feats.cc I only see compressed and sequential matrices, with the exception of htk and sphinx matrices the current script should support all common matrix types.

**Comment by vesis84** [comment]
Hi, is there still the problem? (recently I merged the reading of CM matrices to main branch...)
The `BDM` matrices are supported too (these are not compressed, but stored with 'double' elements).
K.
