### ISSUE TITLE
Support for ranges in script files

### ISSUE THREAD

**Issue by Florian1990** [vesis84/kaldi-io-for-python#21]
Hi,

I noticed that kaldi_io currently does not support [ranges in script files](http://kaldi-asr.org/doc/io.html#io_sec_scp_range). I need this feature so I implemented it [here](https://github.com/Florian1990/kaldi-io-for-python/tree/matrix-range). I guess it is best to generate test cases for that, before I open a pull request. Unfortunately I have no experience with testing in python so far. If you would like to help me with that or could point out a resource, that would be great.

Another point is, that I did not yet fully understand the Kaldi rx/wxfilenames. So I guess you could also add ranges to script file lines like
```utt_id_01002 gunzip -c /usr/data/01002.gz |```
but I am not sure how this would be done.

Thanks for your work on kaldi_io!

**Comment by vesis84** [comment]
Thank you, I opened a PR with this and I will look into it at some point...

The matrix ranges are quite new feature in Kaldi, and up to now, I was not aware that this is already possible with Kaldi I/O.

Could you please prepare some unit test for the new functionality?
It can be a new file similar to 'TEST_COMPRESSED_FEATS.py', for example 'TEST_RANGE_FEATS.py' ...

All the best, and thank you!
Karel

**Comment by vesis84** [comment]
Yesterday, I integrated the support of 'range' in 'scp' files is into the 'master'...
