### ISSUE TITLE
kaldi_io.UnknownMatrixHeader: The header contained 'FV '

### ISSUE THREAD

**Issue by ramesh720** [vesis84/kaldi-io-for-python#24]
can you please tell me how to solve these problem

![image](https://user-images.githubusercontent.com/43946769/50571361-295e9800-0dce-11e9-8845-ee9dbb27848b.png)

**Comment by vesis84** [comment]
Hi, you should not use 'read_mat_scp()', the data format you have should be read with **'read_vec_flt_scp()'**. The data is stored as float-vectors, not matrices...
All best,
Karel
