### ISSUE TITLE
Immediately read a big file after writing it may leads to error ?

### ISSUE THREAD

**Issue by JerryPeng21cuhk** [vesis84/kaldi-io-for-python#25]
I am wondering if we need to wait a thread that writes files to hard-disk in this script. Today I use kaldi_io to write a big file and immediately read it which led to this Error:

```
ivector-mean ark:data/train/spk2utt scp:exp/train_embed_vectors/embeddings.scp 'ark:| copy-vector ark:- ark,scp:exp/train_embed_vectors/spk_embeddings.ark,exp/train_embed_vectors/spk_embeddings.scp' ark,t:exp/train_embed_vectors/num_utts.ark 
WARNING (ivector-mean[5.4.84~1405-c643]:ReadScriptFile():kaldi-table.cc:72) Invalid 148626'th line in script file:"id11251-gFfcgOVmiO0-00006"
WARNING (ivector-mean[5.4.84~1405-c643]:ReadScriptFile():kaldi-table.cc:46) [script file was: exp/train_embed_vectors/embeddings.scp]
ERROR (ivector-mean[5.4.84~1405-c643]:RandomAccessTableReader():util/kaldi-table-inl.h:2512) Error opening RandomAccessTableReader object  (rspecifier is: scp:exp/train_embed_vectors/embeddings.scp)
```

The error will disappear after I manually type this cmd:
```
ivector-mean ark:data/train/spk2utt scp:exp/train_embed_vectors/embeddings.scp 'ark:| copy-vector ark:- ark,scp:exp/train_embed_vectors/spk_embeddings.ark,exp/train_embed_vectors/spk_embeddings.scp' ark,t:exp/train_embed_vectors/num_utts.ark
```
So does this cmd: 
```
copy-vector "scp:echo 'id11251-gFfcgOVmiO0-00006 exp/train_embed_vectors/embeddings.ark:614118526' |" ark,t:-|less
```

I guess the possible reason is that when I reading the newly created big file, the earlier thread is still writing the file.

**Comment by vesis84** [comment]
Hi Jerry, 
to my undestanding, 'kaldi_io' does not use multi-threading and the i/o operations are blocking. So data should be readable immediately after they got written by kaldi_io. There is no thread to wait for, unless you created multi-threading in the python code that uses kaldi_io. 

In the same time, I have seens cases of read errors, when the disk and OS had too much load. Are you writing several of these huge files in the same time, or just one?
K.

**Comment by JerryPeng21cuhk** [comment]
Thanks for your reply. Maybe You are right. I created 32 threads to read files and carry them into GPU in the same time. After I commented those code, the error also disappeared..
