### ISSUE TITLE
appended scp and ark file

### ISSUE THREAD

**Issue by ZaaZoou** [vesis84/kaldi-io-for-python#30]
hello,
i am working on kaldi and i want to try other features, i use kaldi-io-for-python it works, but i want to have the same number of scp and ark file as my number of job, like default kaldi features
but the "open_or_fd" function doesn't have  'ab' mode 
i want to append my ark and scp file
could anyone give some suggestions to do this, please?
Regards !
Zhor
:)

**Comment by vesis84** [comment]
I am not sure what you mean, could you explain it better?

**Comment by kaiyikang** [comment]
I had also tried to use "cat" cmd to solve this problem, but it was not work.
But I found another possible solution, looks like this.

```python
f = kaldi_io.open_or_fd(some_cmd_code, "wb") # open it 
for i in range(some_loop):
    kaldi_io.write_mat(f, your_mat, key=your_key)
f.close()
```
For me, it is work.
