### ISSUE TITLE
Query on wav.scp reader - Streaming audio

### ISSUE THREAD

**Issue by Pradeep-Rangan** [vesis84/kaldi-io-for-python#35]
Hi,

I have found this tool very useful for understanding the kaldi IO mechanisms. I have small query on extracting the samples from streaming speech.

Is it possible using Readhelper to pass the real time audio signal and observe the numpy_array or the samples?

Thanks in advance,

Regards
Pradeep
PhD student
Dept of CSE
IIT Kharagpur

**Comment by vesis84** [comment]
Hi, 
I guess, you ask about a different project (https://pypi.org/project/kaldiio/#readhelper).
This is project 'kaldi_io' and there is no ReadHelper...
Karel
