### ISSUE TITLE
Reading scp files created by subsegment_data_dir.sh

### ISSUE THREAD

**Issue by manojpamk** [vesis84/kaldi-io-for-python#42]
Hi,

I was trying to read mfcc features from a subsegmented directory, i.e created using `utils/data/subsegment_data_dir.sh`. The contents of feats.scp are of the form:

> <ID> <path_to_ark_file>:xx[0:N]

Currently, this cannot be handled by read_mat_scp. Is there any alternative?

**Comment by vesis84** [comment]
Hi, the support was added recently by #38. Please update to latest version...
K.
