### ISSUE TITLE
Add tags for releases

### ISSUE THREAD

**Issue by h-vetinari** [vesis84/kaldi-io-for-python#55]
Last release on [pypi](https://pypi.org/project/kaldi-io/) is 0.9.4, but there are no tags in this repo. For packaging things well in conda-forge, we need to know the relationship between the version and the sources, which is what git tags are for. 🙃 

Could you please add them, ideally also for the last release? (tags can be pushed for past commits as well)

**Comment by h-vetinari** [comment]
From looking at the blame in setup.py, it looks likely that https://github.com/vesis84/kaldi-io-for-python/commit/2df60d791ef287a6df46e2d6bede2c187511d591 corresponds to 0.9.4

**Comment by vesis84** [comment]
Hi, sorry for the delay, the tags are added now. I hope the packaging was okay in the end.
Best regards,
Karel
